import java.util.*;
class ExceptionHandling
{		
		public static void main(String ar[])
		{
				int a,b,c;
				Scanner sc = new Scanner(System.in);
				
				System.out.println("enter 2 nos");
				a = sc.nextInt();
				b = sc.nextInt();
				try
				{	
						c = a/b;
						System.out.println("Division = " + c);
				}
				catch(ArithmeticException e)
				{
						System.out.println("no is 0 so error");
				}
		}
}